# Generated by Django 2.0.6 on 2019-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmvmodel',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
