# Generated by Django 2.0.6 on 2019-03-04 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticationApp', '0002_dmvmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('accountNumber', models.IntegerField(default=0)),
                ('accountBalance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('linkUserForeignKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
